mkdir ~/temp ~/temp/rates ~/temp/credit ~/temp/inflation-swaps ~/temp/equity
cd [path_to_cdm_project]/common-domain-model/rosetta-source/src/main/resources/result-json-files/fpml-5-10/products
cp ./credit/cds-loan-ReferenceObligation-uti.json ~/temp/credit/
cp ./credit/cds-basket-uti.json ~/temp/credit/
cp ./credit/cd-ex01-long-asia-corp-fixreg-versioned.json ~/temp/credit/
cp ./credit/cds-basket-tranche-versioned.json ~/temp/credit/
cp ./credit/cdx-index-option-uti.json ~/temp/credit/
cp ./credit/cds-mortgage-RMBS-versioned.json ~/temp/credit/
cp ./credit/cds-ELCDS-ReferenceObligation-collateral-versioned.json ~/temp/credit/
cp ./credit/cd-swaption-uti.json ~/temp/credit/
cp ./credit/cds-loan-SecuredList-uti.json ~/temp/credit/
cp ./credit/cd-indamt-ex01-short-us-corp-fixreg-versioned.json ~/temp/credit/
cp ./credit/cd-ex02-2003-short-asia-corp-fixreg-versioned.json ~/temp/credit/
cp ./credit/cd-ex16-short-us-corp-fixreg-recovery-factor-versioned.json ~/temp/credit/
cp ./credit/itraxx-index-option-uti.json ~/temp/credit/
cp ./credit/cd-swaption-usi.json ~/temp/credit/
cp ./rates/ird-ex32-zero-coupon-swap-account-versioned.json ~/temp/rates/
cp ./rates/ird-ex22-cap.json ~/temp/rates/
cp ./rates/GBP-Vanilla-uti.json ~/temp/rates/
cp ./rates/ird-ex25-fxnotional-swap-usi-uti.json ~/temp/rates/
cp ./rates/EUR-vanilla-reconciliation-partyB-uti.json ~/temp/rates/
cp ./rates/EUR-Long-Final-Stub-uti.json ~/temp/rates/
cp ./rates/ird-initial-fee.json ~/temp/rates/
cp ./rates/USD-Long-Final-Stub-uti.json ~/temp/rates/
cp ./rates/ird-ex08-fra.json ~/temp/rates/
cp ./rates/EUR-Vanilla-extended-party-roles-versioned.json ~/temp/rates/
cp ./rates/EUR-OIS-uti.json ~/temp/rates/
cp ./rates/CAD-Long-Initial-Stub-versioned.json ~/temp/rates/
cp ./rates/ird-ex14-berm-swaption.json ~/temp/rates/
cp ./rates/ird-ex24-collar.json ~/temp/rates/
cp ./rates/ird-ex11-euro-swaption-partial-auto-ex.json ~/temp/rates/
cp ./rates/ird-ex35-inverse-floater-inverse-vs-floating.json ~/temp/rates/
cp ./rates/ird-ex26-fxnotional-swap-with-cfs.json ~/temp/rates/
cp ./rates/EUR-variable-notional-uti.json ~/temp/rates/
cp ./rates/ird-ex30-swap-comp-avg-relative-date-uti.json ~/temp/rates/
cp ./rates/ird-ex23-floor.json ~/temp/rates/
cp ./rates/GBP-OIS-uti.json ~/temp/rates/
cp ./rates/GBP-VNS-uti.json ~/temp/rates/
cp ./rates/cb-option-usi.json ~/temp/rates/
cp ./rates/EUR-Vanilla-multiple-accounts.json ~/temp/rates/
cp ./rates/ird-xccy-fixed-swap-uti.json ~/temp/rates/
cp ./rates/ird-ex15-amer-swaption.json ~/temp/rates/
cp ./rates/ird-ex27-inverse-floater.json ~/temp/rates/
cp ./rates/EUR-vanilla-reconciliation-partyA-uti.json ~/temp/rates/
cp ./rates/ird-ex09-euro-swaption-explicit-versioned.json ~/temp/rates/
cp ./rates/EUR-Vanilla-party-roles-versioned.json ~/temp/rates/
cp ./rates/ird-xccy-CNH-USD-uti.json ~/temp/rates/
cp ./rates/ird-ex04-arrears-stepup-fee-swap-usi-uti.json ~/temp/rates/
cp ./rates/ird-ex03-compound-swap-versioned.json ~/temp/rates/
cp ./rates/ird-ex34-MXN-swap.json ~/temp/rates/
cp ./rates/ird-ex08-fra-no-discounting.json ~/temp/rates/
cp ./rates/ird-ex02-stub-amort-swap-versioned.json ~/temp/rates/
cp ./rates/EUR-Vanilla-uti.json ~/temp/rates/
cp ./rates/ird-ex01-vanilla-swap-versioned.json ~/temp/rates/
cp ./rates/ird-ex10-euro-swaption-relative-usi.json ~/temp/rates/
cp ./rates/USD-Vanilla-uti.json ~/temp/rates/
cp ./rates/USD-Vanilla-swap.json ~/temp/rates/
cp ./rates/ird-ex06-xccy-swap-uti.json ~/temp/rates/
cp ./rates/EUR-Vanilla-account.json ~/temp/rates/
cp ./rates/ird-ex07-ois-swap-uti.json ~/temp/rates/
cp ./rates/USD-OIS-uti.json ~/temp/rates/
cp ./rates/ird-ex05-long-stub-swap-uti.json ~/temp/rates/
cp ./rates/bond-option-uti.json ~/temp/rates/
cp ./rates/swap-with-other-party-payment.json ~/temp/rates/
cp ./rates/USD-VNS-uti.json ~/temp/rates/
cp ./rates/GBP-Vanilla-person-roles-uti.json ~/temp/rates/
cp ./inflation-swaps/inflation-swap-ex02-yoy-bond-reference.json ~/temp/inflation-swaps/
cp ./inflation-swaps/inflation-swap-ex04-yoy-interp.json ~/temp/inflation-swaps/
cp ./inflation-swaps/inflation-swap-ex05-zc.json ~/temp/inflation-swaps/
cp ./inflation-swaps/inflation-swap-ex01-yoy.json ~/temp/inflation-swaps/
cp ./inflation-swaps/inflation-swap-ex03-yoy-initial-level.json ~/temp/inflation-swaps/
cp ./equity/eqs-ex06-single-index-long-form.json ~/temp/equity/